// Mocks generated by Mockito 5.4.6 from annotations
// in elyx_digital_assignment/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:elyx_digital_assignment/core/error/failures.dart' as _i11;
import 'package:elyx_digital_assignment/core/models/sourced.dart' as _i12;
import 'package:elyx_digital_assignment/core/network/network_info.dart' as _i9;
import 'package:elyx_digital_assignment/core/storage/cache_entry.dart' as _i8;
import 'package:elyx_digital_assignment/features/users/data/datasources/user_local_data_source.dart'
    as _i7;
import 'package:elyx_digital_assignment/features/users/data/datasources/user_remote_data_source.dart'
    as _i5;
import 'package:elyx_digital_assignment/features/users/data/models/github_user_detail_model.dart'
    as _i3;
import 'package:elyx_digital_assignment/features/users/data/models/users_page_model.dart'
    as _i2;
import 'package:elyx_digital_assignment/features/users/domain/entities/github_user_detail.dart'
    as _i14;
import 'package:elyx_digital_assignment/features/users/domain/entities/users_page.dart'
    as _i13;
import 'package:elyx_digital_assignment/features/users/domain/repositories/user_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUsersPageModel_0 extends _i1.SmartFake
    implements _i2.UsersPageModel {
  _FakeUsersPageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGithubUserDetailModel_1 extends _i1.SmartFake
    implements _i3.GithubUserDetailModel {
  _FakeGithubUserDetailModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i5.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.UsersPageModel> getUsers({int? since, int? perPage}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #since: since,
              #perPage: perPage,
            }),
            returnValue: _i6.Future<_i2.UsersPageModel>.value(
              _FakeUsersPageModel_0(
                this,
                Invocation.method(#getUsers, [], {
                  #since: since,
                  #perPage: perPage,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.UsersPageModel>);

  @override
  _i6.Future<_i3.GithubUserDetailModel> getUserDetail(String? login) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDetail, [login]),
            returnValue: _i6.Future<_i3.GithubUserDetailModel>.value(
              _FakeGithubUserDetailModel_1(
                this,
                Invocation.method(#getUserDetail, [login]),
              ),
            ),
          )
          as _i6.Future<_i3.GithubUserDetailModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i7.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> cacheUsersPage(int? cursor, _i2.UsersPageModel? page) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUsersPage, [cursor, page]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i8.CacheEntry<_i3.GithubUserDetailModel>? readUserDetail(String? login) =>
      (super.noSuchMethod(Invocation.method(#readUserDetail, [login]))
          as _i8.CacheEntry<_i3.GithubUserDetailModel>?);

  @override
  _i6.Future<void> cacheUserDetail(_i3.GithubUserDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserDetail, [detail]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, String> displayNames() =>
      (super.noSuchMethod(
            Invocation.method(#displayNames, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.Future<void> clearUsersPages() =>
      (super.noSuchMethod(
            Invocation.method(#clearUsersPages, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i10.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i12.Sourced<_i13.UsersPage>>> getUsers({
    int? cursor,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #cursor: cursor,
              #forceRefresh: forceRefresh,
            }),
            returnValue:
                _i6.Future<
                  _i4.Either<_i11.Failure, _i12.Sourced<_i13.UsersPage>>
                >.value(
                  _FakeEither_2<_i11.Failure, _i12.Sourced<_i13.UsersPage>>(
                    this,
                    Invocation.method(#getUsers, [], {
                      #cursor: cursor,
                      #forceRefresh: forceRefresh,
                    }),
                  ),
                ),
          )
          as _i6.Future<
            _i4.Either<_i11.Failure, _i12.Sourced<_i13.UsersPage>>
          >);

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i12.Sourced<_i14.GithubUserDetail>>>
  getUserDetail(String? login, {bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUserDetail,
              [login],
              {#forceRefresh: forceRefresh},
            ),
            returnValue:
                _i6.Future<
                  _i4.Either<_i11.Failure, _i12.Sourced<_i14.GithubUserDetail>>
                >.value(
                  _FakeEither_2<
                    _i11.Failure,
                    _i12.Sourced<_i14.GithubUserDetail>
                  >(
                    this,
                    Invocation.method(
                      #getUserDetail,
                      [login],
                      {#forceRefresh: forceRefresh},
                    ),
                  ),
                ),
          )
          as _i6.Future<
            _i4.Either<_i11.Failure, _i12.Sourced<_i14.GithubUserDetail>>
          >);

  @override
  _i6.Future<Map<String, String>> cachedDisplayNames() =>
      (super.noSuchMethod(
            Invocation.method(#cachedDisplayNames, []),
            returnValue: _i6.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i6.Future<Map<String, String>>);

  @override
  _i6.Future<void> clearUsersCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearUsersCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
