// Mocks generated by Mockito 5.4.6 from annotations
// in elyx_digital_assignment/test/helpers/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i4;
import 'package:elyx_digital_assignment/core/error/failures.dart' as _i11;
import 'package:elyx_digital_assignment/core/network/network_info.dart' as _i9;
import 'package:elyx_digital_assignment/features/users/data/datasources/user_local_data_source.dart'
    as _i7;
import 'package:elyx_digital_assignment/features/users/data/datasources/user_remote_data_source.dart'
    as _i5;
import 'package:elyx_digital_assignment/features/users/data/models/user_detail_model.dart'
    as _i3;
import 'package:elyx_digital_assignment/features/users/domain/entities/paginated_users.dart'
    as _i2;
import 'package:elyx_digital_assignment/features/users/domain/entities/user_detail.dart'
    as _i12;
import 'package:elyx_digital_assignment/features/users/domain/entities/user_summary.dart'
    as _i8;
import 'package:elyx_digital_assignment/features/users/domain/repositories/user_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePaginatedUsers_0 extends _i1.SmartFake
    implements _i2.PaginatedUsers {
  _FakePaginatedUsers_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDetailModel_1 extends _i1.SmartFake
    implements _i3.UserDetailModel {
  _FakeUserDetailModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i5.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.PaginatedUsers> getUsers({int? since, int? perPage}) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #since: since,
              #perPage: perPage,
            }),
            returnValue: _i6.Future<_i2.PaginatedUsers>.value(
              _FakePaginatedUsers_0(
                this,
                Invocation.method(#getUsers, [], {
                  #since: since,
                  #perPage: perPage,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.PaginatedUsers>);

  @override
  _i6.Future<_i3.UserDetailModel> getUserDetail(String? login) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDetail, [login]),
            returnValue: _i6.Future<_i3.UserDetailModel>.value(
              _FakeUserDetailModel_1(
                this,
                Invocation.method(#getUserDetail, [login]),
              ),
            ),
          )
          as _i6.Future<_i3.UserDetailModel>);
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i7.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> cacheUsersPage(int? since, _i2.PaginatedUsers? page) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUsersPage, [since, page]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cacheUserDetail(_i3.UserDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#cacheUserDetail, [detail]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.UserDetailModel? getCachedUserDetail(String? login) =>
      (super.noSuchMethod(Invocation.method(#getCachedUserDetail, [login]))
          as _i3.UserDetailModel?);

  @override
  List<_i8.UserSummary> getAllCachedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCachedUsers, []),
            returnValue: <_i8.UserSummary>[],
          )
          as List<_i8.UserSummary>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i9.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i10.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i2.PaginatedUsers>> getUsers({
    int? since,
    int? perPage,
    bool? forceRefresh,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, [], {
              #since: since,
              #perPage: perPage,
              #forceRefresh: forceRefresh,
            }),
            returnValue:
                _i6.Future<_i4.Either<_i11.Failure, _i2.PaginatedUsers>>.value(
                  _FakeEither_2<_i11.Failure, _i2.PaginatedUsers>(
                    this,
                    Invocation.method(#getUsers, [], {
                      #since: since,
                      #perPage: perPage,
                      #forceRefresh: forceRefresh,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i11.Failure, _i2.PaginatedUsers>>);

  @override
  _i6.Future<_i4.Either<_i11.Failure, _i12.UserDetail>> getUserDetail(
    String? login,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDetail, [login]),
            returnValue:
                _i6.Future<_i4.Either<_i11.Failure, _i12.UserDetail>>.value(
                  _FakeEither_2<_i11.Failure, _i12.UserDetail>(
                    this,
                    Invocation.method(#getUserDetail, [login]),
                  ),
                ),
          )
          as _i6.Future<_i4.Either<_i11.Failure, _i12.UserDetail>>);
}
